[package]
name = "shooter"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
console_error_panic_hook = "0.1"
shared = { path = "../../shared" }

[profile.dev.package.'*']
opt-level = 3
